### ISSUE TITLE
Remove "with_class" for system-defined classes on Loaders

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#167]
On upcoming versions, [server will stop accepting](https://github.com/aperture-data/athena/pull/705/files) "with_class" + "_ref" for system-defined objects. This will cause ConnectionDataCSV loader to fail for system-defined classes. 

Here is a [draft PR started](https://github.com/aperture-data/aperturedb-python/pull/163) but it is failing tests. Feel free to use it or drop it entirely.

**Comment by gsaluja9** [comment]
This also impacts the DataWizard mechanism.
Also impacted are the Video demos, and possibly other Demos.
Verify that those work as previously.
