### ISSUE TITLE
VideoGeneratorCSV python docs not updated to show video file ingestion

### ISSUE THREAD

**Issue by akshayg-zippin** [aperture-data/aperturedb-python#185]
[This](https://python.docs.aperturedata.io/autoapi/aperturedb/VideoLoader/index.html) URL still shows, what I suppose is, docs for ImageGeneratorCSV.

**Comment by luisremis** [comment]
VideoGeneratorCSV is deprecated. You should use [this](https://python.docs.aperturedata.io/autoapi/aperturedb/VideoDataCSV/index.html).

Take a look and if this is what you are looking for, let us know or close the issue directly.

**Comment by gsaluja9** [comment]
not applicable anymore.
