### ISSUE TITLE
Fix CSV loader example to match new Python API

### ISSUE THREAD

**Issue by vishakha041** [aperture-data/aperturedb-python#301]

**Comment by drewaogle** [comment]
What is the location of the loader example?

**Comment by gsaluja9** [comment]
> What is the location of the loader example?

It's in demos. tutorial/notebooks/02 - DataLoaders.ipynb

**Comment by drewaogle** [comment]
https://github.com/aperture-data/demos/pull/86

**Comment by gsaluja9** [comment]
Resolved by https://github.com/aperture-data/demos/pull/86
