### ISSUE TITLE
ParallelQuery does not fix reference collisions

### ISSUE THREAD

**Issue by bovlb** [aperture-data/aperturedb-python#327]
If a user passes a set of queries to `ParallelQuery` that use references, we don't check for collisions between the references in each query before combining them into one.  This is largely not a problem because the primary client for this class is the CSV loader, which does attempt to generate distinct reference ids (modulo the limit).  This class is documented, however, for clients to use directly and yet this pitfall is not documented.

Suggested mitigations:
* Document the restriction that the client is responsible for ensuring no reference collisions.
* Detect collisions and reject the batch.
* Heal the batch by rewriting references in order to preserve semantics.

**Comment by gsaluja9** [comment]
This was worked upon, and should no longer be the overhead on the client. The duplicate refs are analyzed as the batch is getting converted to the Query, and the logic is follows it to have another pass over the batch and update the references.

https://github.com/aperture-data/aperturedb-python/blob/07ffd5590a2156754b4ba23a97a8b590396e36f5/aperturedb/ParallelQuery.py#L63

It also checks that the batches are kept to a size of 100k ref declarations.

Shall we close this as done?
