### ISSUE TITLE
Support for descriptors on the ObjectMapper API

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#41]
We currently support very basic functionality for descriptors on the OM API (do a similarity search). We should allow users to search for descriptors and retrieve them, similar to what we do for images.

**Comment by gsaluja9** [comment]
This has been [implemented](https://github.com/aperture-data/aperturedb-python/blob/07ffd5590a2156754b4ba23a97a8b590396e36f5/aperturedb/Descriptors.py#L17) . Marking it done.
