### ISSUE TITLE
Intermittent failure in test entity loader.

### ISSUE THREAD

**Issue by gsaluja9** [aperture-data/aperturedb-python#50]
This happens on test run for PR.
On a subsequent run this passed.
There was no code change (just formatting and doc generation related changes)

```
======================================================================
Throughput (imgs/s): 83.37419177859177
FAIL: test_Loader (test_Loaders.TestEntityLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/aperturedb-python/aperturedb-python/test/test_Loaders.py", line 51, in test_Loader
    self.assertEqual(len(generator), dbutils.count_images())
AssertionError: 8000 != 7901

----------------------------------------------------------------------
Ran 8 tests in 275.719s

```
FAILED (failures=1)

**Comment by gsaluja9** [comment]
The number(delta) is indicative of the batch size that is set up in a loader, which seems to indicate that there is a transaction that failed.
One of the transactions did fail, but the response did not have much details to conclude anything.
It read : 

```
[                                         
    {                                     
        "info": "Internal Server Error 1",
        "status": -1                      
    }                                     
]

```
Further enhancements that must be done (for client):

- The implementation of loader does not validate or use the error counter at the moment, and could be enhanced with some Retry logic.
- Also a nice to have would be to have a waterfall display of how the worker threads progress (It would be useful in performance tuning and analysis. _(For the test process, I added some instrumentation to capture time stamps around each query, and persist the response, etc in a sqlite DB)_

**Comment by luisremis** [comment]
this should be fixed now with the update on the server side code
